/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Gestor;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class ReworkUI extends javax.swing.JFrame {
Gestor gestor = new Gestor();
DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Main
     */
    public ReworkUI() {
        initComponents();
        gestor.LoadRwk(tableG, cmbrework);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableG = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbrework = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnSAT = new javax.swing.JButton();
        btnEAT = new javax.swing.JButton();
        txtSerie = new javax.swing.JTextField();
        btnSAT1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnTech = new javax.swing.JMenuItem();
        btnRwk = new javax.swing.JMenuItem();
        btnProdNo = new javax.swing.JMenuItem();
        btnArea = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Technician", "Prod No", "Serial No", "Rework Type", "Description", "Reworker", "Idle Start Time", "Star Activity Time", "End Activity Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableG);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Reworker");

        cmbrework.setEditable(true);

        jLabel2.setText("Serial Number");

        btnSAT.setText("Start Activity Time");
        btnSAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSATActionPerformed(evt);
            }
        });

        btnEAT.setText("End Activity Time");
        btnEAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEATActionPerformed(evt);
            }
        });

        txtSerie.setEditable(false);

        btnSAT1.setText("Select Board");
        btnSAT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbrework, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSerie, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEAT)
                            .addComponent(btnSAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSAT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbrework, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSAT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSAT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEAT))
        );

        jMenu1.setText("File");

        btnTech.setText("Add new Employee");
        btnTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechActionPerformed(evt);
            }
        });
        jMenu1.add(btnTech);

        btnRwk.setText("Add new Reworker");
        btnRwk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRwkActionPerformed(evt);
            }
        });
        jMenu1.add(btnRwk);

        btnProdNo.setText("Add new Prod No");
        btnProdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdNoActionPerformed(evt);
            }
        });
        jMenu1.add(btnProdNo);

        btnArea.setText("Add new Department");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });
        jMenu1.add(btnArea);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechActionPerformed
        // TODO add your handling code here:
        GUI.Technician Tgui = new GUI.Technician();
        Tgui.setVisible(true);
        Tgui.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTechActionPerformed

    private void btnRwkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRwkActionPerformed
        // TODO add your handling code here:
        GUI.Reworker Rgui = new GUI.Reworker();
        Rgui.setVisible(true);
        Rgui.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRwkActionPerformed

    private void btnProdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdNoActionPerformed
        // TODO add your handling code here:
        GUI.ProdNo Pgui = new GUI.ProdNo();
        Pgui.setVisible(true);
        Pgui.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProdNoActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        // TODO add your handling code here:
        GUI.Department Dgui = new GUI.Department();
        Dgui.setVisible(true);
        Dgui.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnSATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSATActionPerformed
        // TODO add your handling code here:
        gestor.SAT(Integer.parseInt(tableG.getValueAt(tableG.getSelectedRow(), 0).toString()));
        gestor.LoadRwk(tableG, cmbrework);
        this.dispose();
    }//GEN-LAST:event_btnSATActionPerformed

    private void btnEATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEATActionPerformed
        // TODO add your handling code here:
        gestor.EAT(Integer.parseInt(tableG.getValueAt(tableG.getSelectedRow(), 0).toString()));
        gestor.LoadRwk(tableG, cmbrework);
        this.dispose();
    }//GEN-LAST:event_btnEATActionPerformed

    private void tableGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableGMouseClicked

    private void btnSAT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAT1ActionPerformed
        // TODO add your handling code here:
        if (tableG.getValueAt(tableG.getSelectedRow(), 1) != null){
            txtSerie.setText(String.valueOf(tableG.getValueAt(tableG.getSelectedRow(), 1)));
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a board from the Table");
        }
    }//GEN-LAST:event_btnSAT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReworkUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnArea;
    private javax.swing.JButton btnEAT;
    private javax.swing.JMenuItem btnProdNo;
    private javax.swing.JMenuItem btnRwk;
    private javax.swing.JButton btnSAT;
    private javax.swing.JButton btnSAT1;
    private javax.swing.JMenuItem btnTech;
    private javax.swing.JComboBox<String> cmbrework;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableG;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
